db:
  image: postgres
  ports:
    - "5432"
rails:
  build: .
  command: bundle exec rails server -p 3000 -b 0.0.0.0
  environment:
    BUNDLE_PATH: /bundle
    RACK_ENV: development
    RAILS_ENV: development
    TESSDATA_PREFIX: "/usr/share/tesseract-ocr"
    AWS_BUCKET: "pancard"
    AWS_REGION: "Singapore"
    AWS_ACCESS_KEY_ID: ""
    AWS_ACCESS_KEY_SECRET: ""

  ports:
    - "3000:3000"
  volumes:
    - .bundle:/bundle
    - .:/rails
  links:
    - db
